version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./memory:/app/memory
      - ./storage:/app/storage
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  vllm:
    build:
      context: ./vllm  # Path to the vllm folder containing the Dockerfile
    ports:
      - "8001:8001"  # Port for the vLLM service
    volumes:
      - ./vllm:/app  # Bind mount for local development
    restart: unless-stopped
    networks:
      - jl-intelligent-agent-system-full_default

networks:
  jl-intelligent-agent-system-full_default:
    name: jl-intelligent-agent-system-full_default
